package nz.ac.aut.ense701.gui;

import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.border.Border;
import javax.swing.border.LineBorder;
import nz.ac.aut.ense701.gameModel.Game;
import nz.ac.aut.ense701.gameModel.Terrain;

/*
 * Panel for representing a single GridSquare of the island on the GUI.
 * 
 * @author AS
 * @version 1.0 - created
 */

public class GridSquarePanel extends javax.swing.JPanel 
{
    /** 
     * Creates new GridSquarePanel.
     * @param game the game to represent
     * @param row the row to represent
     * @param column the column to represent
     */
    public GridSquarePanel(Game game, int row, int column)
    {
        this.game   = game;
        this.row    = row;
        this.column = column;
        initComponents();
    }

    /**
     * Updates the representation of the grid square panel.
     */
    public void update()
    {
        // get the GridSquare object from the world
        Terrain terrain   = game.getTerrain(row, column);
        boolean squareVisible = game.isVisible(row, column);
        boolean squareExplored = game.isExplored(row, column);
        
        Color      color;
        
        switch ( terrain )
        {
            case SAND     : lblText.setIcon(new ImageIcon("src/images/sand.png"));        break;
            case FOREST   : lblText.setIcon(new ImageIcon("src/images/forest.png"));     break;
            case WETLAND  : lblText.setIcon(new ImageIcon("src/images/wetland.png"));           break;
            case SCRUB    : lblText.setIcon(new ImageIcon("src/images/scrub.jpg"));      break;
            case WATER    : lblText.setIcon(new ImageIcon("src/images/water.jpg"));           break;
            default       : color = Color.LIGHT_GRAY;    break;
            
            
            
            //case SAND     : color = Color.YELLOW;        break;
            //case FOREST   : color = Color.GREEN;         break;
            //case WETLAND  : color = Color.BLUE;          break;
            //case SCRUB    : color = Color.DARK_GRAY;     break;
            //case WATER    : color = Color.CYAN;          break;
            //default       : color = Color.LIGHT_GRAY;    break;
 
        }
        
        if ( squareExplored || squareVisible )
        {
            // Set the text of the JLabel if there is a Kiwi in a square
            
            lblText.setText(game.getOccupantStringRepresentation(row,column));
            System.out.println(""+game.getOccupantStringRepresentation(row, column).length());
            if("K".equals(game.getOccupantStringRepresentation(row, column)) || "PK".equals(game.getOccupantStringRepresentation(row, column))){
                lblText.setIcon(new ImageIcon("src/images/cute.jpg"));
                System.out.println("gefds");  
            }
                
            
            //Switch case
            // if T
            //image = ImageIcon("Test.png");

            //lblTxt.setIcon(image)
            // Set the colour. 
            if ( squareVisible && !squareExplored ) 
            {
               // When explored the colour is brighter
               // color = new Color(Math.min(255, color.getRed()   + 128), 
               //                   Math.min(255, color.getGreen() + 128), 
               //                 Math.min(255, color.getBlue()  + 128));
            }
            //lblText.setIcon( icon );
            // set border colour according to 
            // whether the player is in the grid square or not
            setBorder(game.hasPlayer(row,column) ? activeBorder : normalBorder);
            lblText.setHorizontalTextPosition(lblText.CENTER);
        }
        else
        {
            lblText.setText("");
            lblText.setHorizontalTextPosition(lblText.CENTER);
            lblText.setIcon(null);
            //lblText.setIcon(new ImageIcon("src/images/default.jpg")); 
            lblText.setBackground(null);
            setBorder(normalBorder);
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblText = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setLayout(new java.awt.BorderLayout());

        lblText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblText.setText("content");
        lblText.setOpaque(true);
        add(lblText, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblText;
    // End of variables declaration//GEN-END:variables
    
    private Game game;
    private int row, column;
    
    private static final Border normalBorder = new LineBorder(Color.BLACK, 1);
    private static final Border activeBorder = new LineBorder(Color.RED, 3);
}
